### PR TITLE
Enhance bulk upload api to accept zip file

### PR DESCRIPTION
**Pull request by ub0005**
Enhancing Bulk CSV File Upload API to support zip file

### CODE REVIEW

**Comment by NISH1001** [comment]
@ub0005 I was wondering if you're unzipping the file to get back the original csv or not to dump into the db...

**Comment by ub0005** [comment]
> @ub0005 I was wondering if you're unzipping the file to get back the original CSV or not to dump it into the DB...
unzipping is not needed here @NISH1001 Pandas was able to read from the zip file. I tested it by uploading CSV file as well as zip files.

**Comment by NISH1001** [comment]
@ub0005 Everything looks fine from my side as adding this feature doesn't hamper the other functionality. I didn't realize pandas could directly load zip files in `read_csv`. Thanks for pointing that out.

**Review by xhagrg — APPROVED** [review]
The changes can be refactored, but LGTM.

**Review by NISH1001 — APPROVED** [review]
LGTM

**Pull request merged**
