### PR TITLE
Feature/jwt authentication implementation

### PR DESCRIPTION
**Pull request by ub0005**

### CODE REVIEW

**Comment by NISH1001** [comment]
Thanks @ub0005 .
I will also test this and comment if we need other changes...

**Comment by NISH1001** [comment]
@ub0005 Can you please add `jwt` to requirements.txt with proper versioning...

**Comment by NISH1001** [comment]
Tangent:
@ub0005 Can you also please install pre-commit in your virtualenv and run `pre-commit install` at project's root directory. There are a few pre-commit hooks that standardize the codebase. For instance, the code linting is done through `black`.

**Comment by NISH1001** [comment]
@ub0005 I think we need to add  trailing slash to `/login` -> `/login/`

**Comment by NISH1001** [comment]
We need to fix the expiration bug. And we're good to go. Thanks @ub0005 for this auth feature...

**Comment by ub0005** [comment]
Fixed JWT token expiration issue.

**Comment by NISH1001** [comment]
The new change breaks the upload api as you have actually removed the `from datetime import datetime` import.
See:
https://github.com/NASA-IMPACT/HLS-Transfer-Catalog/blob/feature/JWT-Authentication-Implementation/src/app.py#L134=

Here we actually make use of `datetime.now()` to generate a timestamp. 

Rule of thumb:
Before removing imports, please do cross-check on whether that removal hampers other parts of the code...

**Comment by ub0005** [comment]
@NISH1001 Yeah, that was my mistake. I was in the assumption that I have imported the whole DateTime module so nothing will break. Going forward will take care of these confusing things. Thanks for pointing it out and I have reverted that import statement and tested all the endpoints. All the endpoints working fine for me after this fix.

**Pull request merged**
